(()=>{
'use strict';
const boot=document.getElementById('bootState');if(boot){boot.textContent='App architecture loaded';boot.className='badge good'}
window.addEventListener('error',e=>{const s=document.getElementById('status');if(s){s.textContent='Runtime error: '+(e.message||'unknown');s.classList.add('bad')}});

const $=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0,pct=(k,n)=>n?100*k/n:0,fmt=(x,d=1)=>Number(x).toFixed(d);
const RNG=a=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
const normal=r=>{let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(6.283185307*v)};
const hash=(a,b)=>(Math.imul((a>>>0)^Math.imul((b+1)>>>0,374761393),2654435761)>>>0)||1;
function keyed(seed,...vals){let h=seed>>>0;for(const v of vals)h=hash(h,Math.floor(Number(v)*1000));return(h>>>0)/4294967296}
function keyedNormal(seed,...vals){let u=Math.max(1e-9,keyed(seed,...vals,11)),v=Math.max(1e-9,keyed(seed,...vals,29));return Math.sqrt(-2*Math.log(u))*Math.cos(6.283185307*v)}

const MODEL='MK-DIRS-V2.1.1-lab-adversarial-1.0';
const TRACK={balanced:{L:3000,box:185,noise:1,tech:1},technical:{L:3000,box:205,noise:.85,tech:1.55},item:{L:2920,box:145,noise:1.15,tech:.9},straight:{L:3200,box:220,noise:.75,tech:.8},pack:{L:2820,box:168,noise:1.05,tech:1}};
const V1R=[99,99,99,99,14,12,10,8.5,7,6,5,4],V2D=[999,999,999,999,430,370,315,265,225,190,160,135];
const COST={Bullet:.25,Lightning:.30,Golden:.18,Star:.12,'Triple Reds':.10,'Triple Mushrooms':.08,Boo:.06,Red:.035,Mushroom:.025,'Bob-omb':.03,Blue:0};
const STR=['Bagger','Frontrunner','Adaptive','Racer'];
const AIS=['','classic','stop','pulse','late','farmer','opportunistic'];
const STANDARD_ATTACK_AIS=AIS.slice(1),GRACE_ATTACK_AI='graceAbuser';
const ITEMS=['','Bullet','Lightning','Golden','Blue','Triple Reds','Star','Triple Mushrooms','Boo','Red','Mushroom','Green','Banana','Coin','Bob-omb','Triple Greens'];
let archive=null,compactChunks=[],chunkIndex=0,primaryReportText='',primaryReportName='';

function cfg(){
  let baggers=clamp(+$('baggers').value||0,0,8),fronts=clamp(+$('fronts').value||0,0,8);if(baggers+fronts>10)fronts=10-baggers;
  let capture=$('capture').value,races=clamp(+$('races').value||300,50,3000);if(capture==='frame'&&races>100){races=100;$('races').value=100;$('status').textContent='Full-frame capture is capped at 100 paired races.'}
  return{races,seed:clamp(+$('seed').value||2408,1,99999999),baggers,fronts,track:$('track').value,skill:$('skill').value,bagAI:$('bagAI').value,chaos:+$('chaos').value,pack:+$('pack').value,blue:+$('blue').value,lapAccel:+$('lapAccel').value,v1Strict:+$('v1Strict').value,distanceReq:+$('distanceReq').value,effortWindow:+$('effortWindow').value,effortSens:+$('effortSens').value,debtPerPlace:+$('debtPerPlace').value,creditSpend:+$('creditSpend').value,frontDecay:+$('frontDecay').value,grace:+$('grace').value,capture}
}
function skillValue(r,k,i){if(k==='equal')return clamp(.67+normal(r)*.055,.48,.85);if(k==='elite')return clamp(.81+normal(r)*.065,.62,.98);if(k==='split')return i%2?clamp(.39+normal(r)*.08,.12,.59):clamp(.84+normal(r)*.055,.68,.98);return clamp(.56+normal(r)*.18,.10,.98)}
function makeRoster(seed,c){const r=RNG(seed),types=[];for(let i=0;i<c.baggers;i++)types.push('Bagger');for(let i=0;i<c.fronts;i++)types.push('Frontrunner');while(types.length<12)types.push(types.length%3?'Racer':'Adaptive');for(let i=11;i>0;i--){let j=Math.floor(r()*(i+1));[types[i],types[j]]=[types[j],types[i]]}const hostile=AIS.slice(1);return types.map((strategy,i)=>({id:i,strategy,bagAI:strategy==='Bagger'?(c.bagAI==='mix'?hostile[Math.floor(r()*hostile.length)]:c.bagAI):'',skill:skillValue(r,c.skill,i),itemSkill:clamp(.52+normal(r)*.18,.08,.98),consistency:clamp(.64+normal(r)*.15,.18,.98),aggression:clamp(.50+normal(r)*.20,.08,.96),risk:clamp(.50+normal(r)*.20,.08,.98)}))}

// Frozen steering schedule: no comeback-credit or system-state inputs, and never >1.0 pace.
function plannedIntent(p,t){
  if(p.strategy!=='Bagger')return 1;
  // Attack-only adversary: races normally until disruption grace exists, then deliberately sheds speed.
  // This changes attacker behavior only; V2.1 mechanics remain frozen.
  if(p.bagAI===GRACE_ATTACK_AI)return p.graceLeft>0?.08:1;
  if(p.bagAI==='stop')return t<12?.08:t<22?.48:1;
  if(p.bagAI==='pulse')return t<34?(Math.floor(t/2)%2?1:.46):1;
  if(p.bagAI==='late')return t>=28&&t<53?.58:1;
  if(p.bagAI==='farmer')return t<39?.68:1;
  if(p.bagAI==='opportunistic')return t<12?.9:t<28?.72:t<40?.92:1;
  return t<30?.62:1;
}
function effortCurve(ratio,sensitivity){let q=clamp(1-(1-ratio)*sensitivity,0,1.1);if(q>=.9)return clamp(.95+(q-.9)*.5,.95,1);if(q>=.8)return .75+(q-.8)*2;if(q>=.7)return .40+(q-.7)*3.5;if(q>=.6)return .10+(q-.6)*3;if(q>=.5)return q-.5;return 0}
const ceiling=pos=>clamp(.10+Math.pow((pos-1)/11,.92)*.90,.10,1);
function openingItem(u){const a=['Mushroom','Triple Mushrooms','Red','Triple Greens','Bob-omb','Banana'];return a[Math.min(a.length-1,Math.floor(u*a.length))]}
function itemFor(power,u){if(power>.82){if(u<.14)return'Bullet';if(u<.31)return'Lightning';if(u<.53)return'Golden';if(u<.76)return'Triple Reds';return'Star'}if(power>.64){if(u<.23)return'Star';if(u<.48)return'Triple Mushrooms';if(u<.70)return'Triple Reds';return'Boo'}if(power>.42){if(u<.30)return'Red';if(u<.58)return'Mushroom';if(u<.78)return'Green';return'Bob-omb'}return u<.46?'Coin':u<.74?'Banana':'Green'}
function snapshotMarks(capture){if(capture==='deep')return Array.from({length:51},(_,i)=>i/50);return Array.from({length:11},(_,i)=>i/10)}

function simulate(roster,c,mode,seed,keepDetails=true){
  const T=TRACK[c.track],dt=.5,marks=snapshotMarks(c.capture),histN=Math.max(1,Math.round(c.effortWindow/dt));
  const P=roster.map(p=>({...p,x:keyed(seed,p.id,1)*2,finishTime:0,finalPosition:12,position:12,lastPosition:12,erp:12,credit:0,debt:0,debtAdded:0,debtRepaid:0,launderedLosses:0,avoidedDebt:0,graceAbuseSeconds:0,driverIntent:1,wasInGrace:false,gainStreak:0,validatedLossStreak:0,voluntaryLosses:0,slow:0,graceLeft:0,rollingEffort:1,effortHistory:Array(histN).fill(1),effortSum:0,effortSamples:0,creditSpent:0,sacrificeSeconds:0,powerSum:0,itemCount:0,hitsTaken:0,lastBox:-1,bagged:false,snapshots:[],frames:[]}));
  const events=[],seen=new Set();let t=0,tick=0,finishCount=0,firstSet=true;
  const rank=()=>{P.sort((a,b)=>a.finishTime&&b.finishTime?a.finishTime-b.finishTime:a.finishTime?-1:b.finishTime?1:b.x-a.x||a.id-b.id);P.forEach((p,i)=>p.position=i+1)};
  rank();P.forEach(p=>{p.lastPosition=p.position;p.erp=p.position});

  while(t<220&&P.some(p=>!p.finishTime)){
    rank();const med=[...P].sort((a,b)=>a.x-b.x)[5].x;
    for(const p of P){
      if(p.finishTime)continue;
      const lap=Math.min(3,Math.floor(p.x/(T.L/3))+1),frac=p.x/T.L,basePace=25.3+4.05*p.skill,intent=plannedIntent(p,t);
      if(p.strategy==='Bagger'&&intent<.9){p.bagged=true;p.sacrificeSeconds+=(1-intent)*dt}
      const slowMult=p.slow>0?.43:1;if(p.slow>0)p.slow=Math.max(0,p.slow-dt);
      const inGrace=p.graceLeft>0;if(inGrace)p.graceLeft=Math.max(0,p.graceLeft-dt);p.wasInGrace=inGrace;p.driverIntent=intent;if(inGrace&&intent<.9)p.graceAbuseSeconds+=dt;
      const rawRatio=inGrace?1:intent*slowMult;p.effortHistory.push(rawRatio);while(p.effortHistory.length>histN)p.effortHistory.shift();
      const rollingRatio=avg(p.effortHistory),effort=inGrace?1:effortCurve(rollingRatio,c.effortSens);p.rollingEffort=effort;p.effortSum+=effort;p.effortSamples++;
      const catchup=p.x<med?Math.min(1.5,(med-p.x)/220)*.72*c.pack*(c.track==='pack'?1.35:1):0;
      const noise=keyedNormal(seed,100,tick,p.id)*(1-p.consistency)*.72*c.chaos*T.noise;
      const speed=Math.max(2,basePace*intent*slowMult+noise+catchup),dx=speed*dt;p.x+=dx;
      const virtualDistance=inGrace?Math.max(dx,basePace*dt*.92):dx*effort;

      if(mode==='v1'){
        if(p.position>=5)p.credit=clamp(p.credit+dt*(1+(lap-1)*c.lapAccel)/(V1R[p.position-1]*c.v1Strict),0,1);else p.credit=clamp(p.credit-.006,0,1);
      }
      if(mode==='v2'){
        let earnDist=virtualDistance;
        if(p.debt>0){const before=p.debt,repay=Math.min(p.debt,earnDist);p.debt-=repay;p.debtRepaid+=repay;earnDist-=repay;if(keepDetails&&before>0&&p.debt<=1e-9)events.push({time:t,type:'debt_cleared',player:p.id,totalRepaid:p.debtRepaid})}
        if(p.position<p.erp)p.erp=p.position;
        if(p.position>p.erp&&earnDist>0){const catchRate=earnDist*(1+(lap-1)*c.lapAccel)/(112*c.distanceReq)*(1+.035*Math.max(0,p.position-5));p.erp=Math.min(p.position,p.erp+catchRate)}
        if(p.position>=5&&earnDist>0){const rp=clamp(Math.round(p.erp),5,12),req=V2D[rp-1]*c.distanceReq;p.credit=clamp(p.credit+earnDist*(1+(lap-1)*c.lapAccel)/req,0,1)}
        if(p.position<=4)p.credit=clamp(p.credit-c.frontDecay*dt,0,1);
      }

      const box=Math.floor(p.x/T.box);
      if(box>p.lastBox){
        p.lastBox=box;const opening=firstSet&&p.x<265;let power,item;
        if(opening){power=.54+keyed(seed,200,p.id,box)*.16;item=openingItem(keyed(seed,201,p.id,box))}
        else{
          power=mode==='instant'?ceiling(p.position):mode==='v1'?clamp(.10+p.credit*(ceiling(p.position)-.10),.08,1):clamp(.10+p.credit*(ceiling(p.erp)-.10),.08,1);
          item=itemFor(power,keyed(seed,202,p.id,box));
          // V2.1 Blue Shell is a race-state/leader-control item, not a deep-comeback item.
          if(mode==='v2'&&c.blue>0&&p.position>=4&&p.position<=10){const leader=[...P].filter(z=>!z.finishTime).sort((a,b)=>b.x-a.x)[0],gap=leader?Math.max(0,leader.x-p.x):0,blueChance=.012*c.blue*(lap===1?.55:lap===2?1:1.25)*(gap>180?1.5:gap>90?1.15:.7);if(keyed(seed,203,p.id,box)<blueChance)item='Blue'}
        }
        p.powerSum+=power;p.itemCount++;let creditCost=0;if(mode==='v2'&&!opening){creditCost=(COST[item]||0)*c.creditSpend;p.credit=clamp(p.credit-creditCost,0,1);p.creditSpent+=creditCost}
        const boostRand=.65+keyed(seed,204,p.id,box)*.7;let boost=(1.4+10.5*power+4.4*p.itemSkill)*boostRand;if(item==='Bullet')boost+=30;if(item==='Golden')boost+=17;if(item==='Star')boost+=10;if(item==='Triple Mushrooms')boost+=7;p.x+=boost;
        if(keepDetails)events.push({time:t,type:'item_draw',player:p.id,item,position:p.position,erp:p.erp,creditAfter:p.credit,debt:p.debt,rollingEffort:effort,power,creditCost,distance:p.x,lap,opening});
        if(item==='Blue'&&c.blue>0){const q=[...P].filter(z=>!z.finishTime).sort((a,b)=>b.x-a.x)[0];if(q&&q.id!==p.id&&keyed(seed,205,p.id,box)<.72){q.x=Math.max(0,q.x-14-10*keyed(seed,206,p.id,box));q.hitsTaken++;q.slow=2.4;q.graceLeft=c.grace;if(keepDetails)events.push({time:t,type:'hit',attacker:p.id,target:q.id,item:'Blue',attackerPosition:p.position,targetPosition:q.position,targetGrace:c.grace,distance:q.x})}}
        else if(['Red','Triple Reds','Green','Lightning','Bob-omb'].includes(item)&&keyed(seed,207,p.id,box)<(.14+.36*power)*p.aggression*c.chaos){const q=P.filter(z=>!z.finishTime&&z.x>p.x&&z.x-p.x<175).sort((a,b)=>a.x-b.x)[0];if(q){q.x=Math.max(0,q.x-(2.5+10.5*power)*(.72+keyed(seed,208,p.id,box)*.7));q.hitsTaken++;q.slow=item==='Lightning'?2.8:1.8;q.graceLeft=c.grace;if(keepDetails)events.push({time:t,type:'hit',attacker:p.id,target:q.id,item,attackerPosition:p.position,targetPosition:q.position,targetGrace:c.grace,distance:q.x})}}
      }

      if(keyed(seed,300,tick,p.id)<.00125*T.tech*c.chaos*(1-p.consistency)){p.slow=1.5+keyed(seed,301,tick,p.id)*1.4;p.graceLeft=c.grace;p.x=Math.max(0,p.x-2-keyed(seed,302,tick,p.id)*5);if(keepDetails)events.push({time:t,type:'track_disruption',player:p.id,position:p.position,grace:c.grace,distance:p.x})}
      if(p.x>=T.L){p.x=T.L;p.finishTime=t;p.finalPosition=++finishCount;if(keepDetails)events.push({time:t,type:'finish',player:p.id,finalPosition:p.finalPosition})}
    }

    firstSet=false;rank();
    for(const p of P)if(p.lastPosition!==p.position){
      const delta=p.lastPosition-p.position,from=p.lastPosition,to=p.position;
      if(mode==='v1'){
        if(delta>0){p.gainStreak+=delta;p.validatedLossStreak=0;p.credit=clamp(p.credit+.012*delta*(1+.18*Math.min(6,p.gainStreak)),0,1)}
        else{p.validatedLossStreak+=-delta;p.gainStreak=0;p.credit=clamp(p.credit-.055*(-delta)/(1+.28*Math.min(8,p.validatedLossStreak)),0,1)}
      }
      if(mode==='v2'){
        if(delta>0){p.erp=Math.min(p.erp,p.position);p.gainStreak+=delta;p.validatedLossStreak=0}
        else{
          const loss=-delta,validated=p.graceLeft>0||p.slow>0||p.rollingEffort>=.78;let debtAdded=0;
          // Telemetry only: low driver intent hidden inside disruption grace is a potentially laundered loss.
          // It does NOT change classification, debt, credit, ERP, or item behavior.
          const graceLaundered=validated&&p.wasInGrace&&p.driverIntent<.9;
          if(graceLaundered){p.launderedLosses+=loss;p.avoidedDebt+=loss*c.debtPerPlace}
          if(validated){p.validatedLossStreak+=loss;p.credit=clamp(p.credit-.02*loss/(1+.20*Math.min(8,p.validatedLossStreak)),0,1)}
          else{p.validatedLossStreak=0;p.voluntaryLosses+=loss;debtAdded=loss*c.debtPerPlace;p.debt+=debtAdded;p.debtAdded+=debtAdded;p.credit=clamp(p.credit-.035*loss,0,1)}
          if(keepDetails)events.push({time:t,type:'position_loss_classified',player:p.id,from,to,validated,rollingEffort:p.rollingEffort,driverIntent:p.driverIntent,inGrace:p.wasInGrace,graceLaundered,graceLeft:p.graceLeft,creditAfter:p.credit,erp:p.erp,debtAdded,debt:p.debt,avoidedDebt:graceLaundered?loss*c.debtPerPlace:0});
        }
      }
      p.lastPosition=p.position;
    }

    const lead=Math.max(...P.map(p=>p.x))/T.L;
    for(const m of marks)if(lead>=m&&!seen.has(m)){seen.add(m);rank();P.forEach(p=>p.snapshots.push({raceProgress:m,position:p.position,erp:p.erp,credit:p.credit,effort:p.rollingEffort,debt:p.debt,distance:p.x,lap:Math.min(3,Math.floor(p.x/(T.L/3))+1),sacrificeSeconds:p.sacrificeSeconds,voluntaryLosses:p.voluntaryLosses,validatedLossStreak:p.validatedLossStreak,creditSpent:p.creditSpent,hitsTaken:p.hitsTaken}))}
    if(c.capture==='frame'&&keepDetails){rank();P.forEach(p=>p.frames.push({time:t,position:p.position,erp:p.erp,credit:p.credit,effort:p.rollingEffort,debt:p.debt,distance:p.x,lap:Math.min(3,Math.floor(p.x/(T.L/3))+1),sacrificeSeconds:p.sacrificeSeconds,voluntaryLosses:p.voluntaryLosses,creditSpent:p.creditSpent,hitsTaken:p.hitsTaken}))}
    t+=dt;tick++;
  }

  rank();P.forEach((p,i)=>{if(!p.finalPosition)p.finalPosition=i+1;while(p.snapshots.length<marks.length){const m=marks[p.snapshots.length];p.snapshots.push({raceProgress:m,position:p.finalPosition,erp:p.erp,credit:p.credit,effort:p.rollingEffort,debt:p.debt,distance:p.x,lap:3,sacrificeSeconds:p.sacrificeSeconds,voluntaryLosses:p.voluntaryLosses,validatedLossStreak:p.validatedLossStreak,creditSpent:p.creditSpent,hitsTaken:p.hitsTaken})}});
  return{seed,mode,trackLength:T.L,players:P.sort((a,b)=>a.id-b.id).map(p=>({id:p.id,strategy:p.strategy,bagAI:p.bagAI,skill:p.skill,itemSkill:p.itemSkill,consistency:p.consistency,aggression:p.aggression,risk:p.risk,finalPosition:p.finalPosition,finishTime:p.finishTime,bagged:p.bagged,sacrificeSeconds:p.sacrificeSeconds,voluntaryLosses:p.voluntaryLosses,validatedLossStreak:p.validatedLossStreak,debtAdded:p.debtAdded,debtRepaid:p.debtRepaid,finalDebt:p.debt,launderedLosses:p.launderedLosses,avoidedDebt:p.avoidedDebt,graceAbuseSeconds:p.graceAbuseSeconds,creditSpent:p.creditSpent,hitsTaken:p.hitsTaken,averageEffort:p.effortSamples?p.effortSum/p.effortSamples:1,averageItemPower:p.itemCount?p.powerSum/p.itemCount:0,itemCount:p.itemCount,snapshots:p.snapshots,frames:c.capture==='frame'?p.frames:undefined})),events};
}

function solveLinear(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let piv=i;for(let j=i+1;j<n;j++)if(Math.abs(M[j][i])>Math.abs(M[piv][i]))piv=j;[M[i],M[piv]]=[M[piv],M[i]];if(Math.abs(M[i][i])<1e-9)continue;const d=M[i][i];for(let k=i;k<=n;k++)M[i][k]/=d;for(let j=0;j<n;j++)if(j!==i){const f=M[j][i];for(let k=i;k<=n;k++)M[j][k]-=f*M[i][k]}}return M.map(r=>r[n])}
function adjustedSacrificeSlope(records){if(records.length<12)return 0;const aiLevels=AIS.slice(2),p=3+aiLevels.length,xtx=Array.from({length:p},()=>Array(p).fill(0)),xty=Array(p).fill(0);for(const r of records){const x=[1,r.sacrifice,r.skill,...aiLevels.map(a=>r.ai===a?1:0)],y=r.finish;for(let i=0;i<p;i++){xty[i]+=x[i]*y;for(let j=0;j<p;j++)xtx[i][j]+=x[i]*x[j]}}return solveLinear(xtx,xty)[1]||0}
function aggregate(races,mode){
  const S={};STR.forEach(k=>S[k]={n:0,finish:0,wins:0,top3:0,bottom4:0,power:0,items:0,sacrifice:0,skill:0});const AI={};AIS.slice(1).forEach(a=>AI[a]={n:0,finish:0,wins:0,top3:0,bottom4:0,sacrifice:0});
  let bN=0,b3=0,bW=0,bB4=0,pairs=[],bagRecords=[];
  for(const z of races)for(const p of z.players){const s=S[p.strategy];s.n++;s.finish+=p.finalPosition;s.skill+=p.skill;s.power+=p.averageItemPower*p.itemCount;s.items+=p.itemCount;s.sacrifice+=p.sacrificeSeconds;if(p.finalPosition===1)s.wins++;if(p.finalPosition<=3)s.top3++;if(p.finalPosition>=9)s.bottom4++;if(p.strategy==='Bagger'&&p.bagged){bN++;if(p.finalPosition<=3)b3++;if(p.finalPosition===1)bW++;if(p.finalPosition>=9)bB4++;bagRecords.push({sacrifice:p.sacrificeSeconds,skill:p.skill,ai:p.bagAI,finish:p.finalPosition});const a=AI[p.bagAI];if(a){a.n++;a.finish+=p.finalPosition;a.sacrifice+=p.sacrificeSeconds;if(p.finalPosition===1)a.wins++;if(p.finalPosition<=3)a.top3++;if(p.finalPosition>=9)a.bottom4++}}pairs.push([p.skill,13-p.finalPosition])}
  let mx=avg(pairs.map(x=>x[0])),my=avg(pairs.map(x=>x[1])),nu=0,dx=0,dy=0;for(const[x,y]of pairs){nu+=(x-mx)*(y-my);dx+=(x-mx)**2;dy+=(y-my)**2}
  return{mode,strategies:S,bagAI:AI,baggerTrials:bN,baggerTop3:b3,baggerWins:bW,baggerBottom4:bB4,skillCorrelation:dx&&dy?nu/Math.sqrt(dx*dy):0,adjustedSacrificeSlope:adjustedSacrificeSlope(bagRecords)};
}
function pairedHealth(raw){const out={instant:{gN:0,g4:0,fN:0,f3:0,dN:0,disp:0},v1:{gN:0,g4:0,fN:0,f3:0,dN:0,disp:0},v2:{gN:0,g4:0,fN:0,f3:0,dN:0,disp:0}};for(let i=0;i<raw.instant.length;i++){const base=raw.instant[i],halfIndex=Math.floor((base.players[0].snapshots.length-1)/2),gIDs=base.players.filter(p=>p.strategy!=='Bagger'&&p.snapshots[halfIndex].position>=9).map(p=>p.id),fIDs=base.players.filter(p=>p.strategy!=='Bagger'&&p.snapshots[halfIndex].position<=3).map(p=>p.id),dIDs=base.players.filter(p=>p.strategy!=='Bagger'&&p.snapshots[halfIndex].position<=6).map(p=>p.id);for(const mode of['instant','v1','v2']){const z=raw[mode],race=z[i],m=out[mode];m.gN+=gIDs.length;m.fN+=fIDs.length;m.dN+=dIDs.length;for(const id of gIDs)if(race.players[id].finalPosition<=4)m.g4++;for(const id of fIDs)if(race.players[id].finalPosition<=3)m.f3++;for(const id of dIDs){const p=race.players[id];if(p.finalPosition>6&&race.players.some(q=>q.strategy==='Bagger'&&q.finalPosition<p.finalPosition))m.disp++}}}return out}
function roi(X){const b=X.strategies.Bagger,r=X.strategies.Racer;if(!b.n||!r.n)return null;return(r.finish/r.n-b.finish/b.n)-((b.skill/b.n-r.skill/r.n)*7.2)}
function wilson(k,n){if(!n)return'—';const z=1.96,p=k/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,m=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/d;return`${(100*p).toFixed(1)}% · 95% CI ${(100*(c-m)).toFixed(1)}–${(100*(c+m)).toFixed(1)}`}
function metricCard(name,I,V1,V2,goal,ci){const d=V2-I,good=goal==='down'?d<0:goal==='up'?d>0:Math.abs(d)<5;return`<div class="stat"><div class="small muted">${name}</div><div class="num">${V2.toFixed(1)}%</div><div class="tiny muted">Instant ${I.toFixed(1)} · V1 ${V1.toFixed(1)} · V2.1 ${V2.toFixed(1)}</div><div class="tiny ${good?'good':'warn'}" style="margin-top:5px">${good?'Healthy direction':'Inspect'}</div><div class="tiny muted">${ci}</div></div>`}
function compareLine(name,I,V1,V2,note){return`<div class="metricline"><div class="metrichead"><span>${name}</span><span>${I.toFixed(1)} → ${V1.toFixed(1)} → <b>${V2.toFixed(1)}</b></span></div><div class="tiny muted">${note}</div></div>`}
function gate(name,pass,why){return`<div class="gate"><div class="metrichead"><b>${name}</b><span class="pill ${pass?'good':'bad'}">${pass?'PASS':'FAIL'}</span></div><div class="tiny muted" style="margin-top:5px">${why}</div></div>`}
function renderSummary(){
  const I=archive.summary.instant,V1=archive.summary.v1,V2=archive.summary.v2,H=archive.pairedHealth;
  const ib=pct(I.baggerTop3,I.baggerTrials),b1=pct(V1.baggerTop3,V1.baggerTrials),b2=pct(V2.baggerTop3,V2.baggerTrials),iw=pct(I.baggerWins,I.baggerTrials),w1=pct(V1.baggerWins,V1.baggerTrials),w2=pct(V2.baggerWins,V2.baggerTrials),i4=pct(I.baggerBottom4,I.baggerTrials),q1=pct(V1.baggerBottom4,V1.baggerTrials),q2=pct(V2.baggerBottom4,V2.baggerTrials);
  const ig=pct(H.instant.g4,H.instant.gN),g1=pct(H.v1.g4,H.v1.gN),g2=pct(H.v2.g4,H.v2.gN),iff=pct(H.instant.f3,H.instant.fN),f1=pct(H.v1.f3,H.v1.fN),f2=pct(H.v2.f3,H.v2.fN),id=pct(H.instant.disp,H.instant.dN),d1=pct(H.v1.disp,H.v1.dN),d2=pct(H.v2.disp,H.v2.dN),r2=roi(V2);
  const checks=[b2<=ib-5,w2<=iw-2,g2>=ig-5,Math.abs(f2-iff)<=8,d2<=id+2,r2==null||r2<0],pass=checks.filter(Boolean).length;
  $('verdict').innerHTML=`<span class="badge">V2.1 ${pass}/6 design gates</span><h2 style="margin-top:8px">${pass>=5?'V2.1 is behaving like an anti-bagging system.':pass>=3?'V2.1 is promising, but still leaking advantage somewhere.':'V2.1 is failing the design goal in this configuration.'}</h2><p class="muted small">Race-health metrics below use the same Instant-defined players across all three systems. Steering schedules and exogenous random streams are paired.</p>`;
  $('gates').innerHTML=gate('Bagging top-3',checks[0],`Target ≤ Instant −5 pts · current Δ ${(b2-ib).toFixed(1)}`)+gate('Bagging wins',checks[1],`Target ≤ Instant −2 pts · current Δ ${(w2-iw).toFixed(1)}`)+gate('Genuine comeback',checks[2],`Fixed cohort · current Δ ${(g2-ig).toFixed(1)}`)+gate('Frontrunner health',checks[3],`Fixed cohort · current Δ ${(f2-iff).toFixed(1)}`)+gate('Collateral displacement',checks[4],`Fixed cohort · current Δ ${(d2-id).toFixed(1)}`)+gate('Bagging ROI',checks[5],`Negative is ideal · current ${r2==null?'—':r2.toFixed(2)+' positions'}`);
  $('metricCards').innerHTML=metricCard('Bagger top-3',ib,b1,b2,'down',wilson(V2.baggerTop3,V2.baggerTrials))+metricCard('Bagger wins',iw,w1,w2,'down',wilson(V2.baggerWins,V2.baggerTrials))+metricCard('Bagger bottom-4',i4,q1,q2,'up',wilson(V2.baggerBottom4,V2.baggerTrials))+metricCard('Fixed-cohort comeback → top 4',ig,g1,g2,'same',wilson(H.v2.g4,H.v2.gN))+metricCard('Fixed-cohort top-3 retained',iff,f1,f2,'same',wilson(H.v2.f3,H.v2.fN))+metricCard('Fixed-cohort displacement',id,d1,d2,'down',wilson(H.v2.disp,H.v2.dN));
  $('bagMetrics').innerHTML=compareLine('Top-3 success',ib,b1,b2,'lower is better')+compareLine('Win rate',iw,w1,w2,'lower is better')+compareLine('Bottom-4 risk',i4,q1,q2,'higher makes bagging a gamble')+compareLine('Collateral displacement',id,d1,d2,'fixed Instant-defined cohort');
  $('healthMetrics').innerHTML=compareLine('Genuine comeback',ig,g1,g2,'same Instant-defined backmarkers')+compareLine('Frontrunner retention',iff,f1,f2,'same Instant-defined leaders')+compareLine('Skill ↔ result',I.skillCorrelation*100,V1.skillCorrelation*100,V2.skillCorrelation*100,'moderate change only');
  let rows='';for(const X of[I,V1,V2])for(const k of STR){const s=X.strategies[k];if(!s.n)continue;rows+=`<tr><td>${X.mode==='v2'?'v2.1':X.mode}</td><td>${k}</td><td>${(s.finish/s.n).toFixed(2)}</td><td>${wilson(s.wins,s.n)}</td><td>${wilson(s.top3,s.n)}</td><td>${wilson(s.bottom4,s.n)}</td><td>${s.items?(100*s.power/s.items).toFixed(0)+'%':'—'}</td><td>${k==='Bagger'?(s.sacrifice/s.n).toFixed(1)+'s':'—'}</td></tr>`}$('strategyRows').innerHTML=rows;
  let aiRows='';for(const a of AIS.slice(1))for(const X of[I,V1,V2]){const s=X.bagAI[a];if(!s||!s.n)continue;aiRows+=`<tr><td>${a}</td><td>${X.mode==='v2'?'v2.1':X.mode}</td><td>${s.n}</td><td>${(s.finish/s.n).toFixed(2)}</td><td>${pct(s.wins,s.n).toFixed(1)}%</td><td>${pct(s.top3,s.n).toFixed(1)}%</td><td>${pct(s.bottom4,s.n).toFixed(1)}%</td><td>${(s.sacrifice/s.n).toFixed(1)}s</td></tr>`}$('bagAIrows').innerHTML=aiRows;
  const rI=roi(I),r1=roi(V1);$('roiBox').innerHTML=`<div class="stat" style="border:0;padding:0"><div class="num">${r2==null?'—':(r2>=0?'+':'')+r2.toFixed(2)}</div><p class="small muted">Skill-adjusted expected-position advantage for V2.1 baggers. Negative is ideal.</p><div class="tiny muted">Instant ${rI==null?'—':rI.toFixed(2)} · V1 ${r1==null?'—':r1.toFixed(2)}</div></div>`;
  $('slopeBox').innerHTML=`<div class="stat" style="border:0;padding:0"><div class="num">${V2.adjustedSacrificeSlope>=0?'+':''}${V2.adjustedSacrificeSlope.toFixed(2)}</div><p class="small muted">Finish-position change per second sacrificed after controlling for skill and bagger AI. Positive means sacrifice hurts.</p><div class="tiny muted">V1 ${V1.adjustedSacrificeSlope>=0?'+':''}${V1.adjustedSacrificeSlope.toFixed(2)}</div></div>`;
  $('skillBox').innerHTML=`<div class="stat" style="border:0;padding:0"><div class="num">${(V2.skillCorrelation*100).toFixed(1)}%</div><p class="small muted">V2.1 correlation between driving skill and final result.</p><div class="tiny muted">Instant ${(I.skillCorrelation*100).toFixed(1)}% · V1 ${(V1.skillCorrelation*100).toFixed(1)}%</div></div>`;
}

function lineChart(series,minY,maxY,labels,invert=false){const colors=['var(--s1)','var(--s2)','var(--s3)'],w=100,h=28,pad=2,ymap=v=>invert?pad+(h-2*pad)*(v-minY)/(maxY-minY||1):pad+(h-2*pad)*(maxY-v)/(maxY-minY||1);let grid='';for(let i=0;i<=4;i++){let x=i*25;grid+=`<line x1="${x}" y1="${pad}" x2="${x}" y2="${h-pad}" stroke="var(--border)" stroke-width=".18"/>`}let paths=series.map((arr,i)=>`<polyline points="${arr.map(q=>`${q[0]*100},${ymap(q[1])}`).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width=".72" vector-effect="non-scaling-stroke"/>`).join(''),legend=labels.map((x,i)=>`<span class="key"><span class="sw" style="background:${colors[i]}"></span>${x}</span>`).join('');return`<svg viewBox="0 0 ${w} ${h}" style="width:100%;display:block">${grid}${paths}</svg><div class="chartlegend">${legend}</div>`}
function currentRace(){if(!archive)return null;return archive.races[$('inspectMode').value][+$('racePick').value||0]}
function initInspector(){if(!archive)return;$('racePick').innerHTML=archive.races.v2.map((_,i)=>`<option value="${i}">Race ${i+1}</option>`).join('');renderRaceInspector()}
function renderRaceInspector(){const z=currentRace();if(!z)return;const old=$('playerPick').value;$('playerPick').innerHTML=z.players.map(p=>`<option value="${p.id}">P${p.id+1} · ${p.strategy}${p.bagAI?' / '+p.bagAI:''}</option>`).join('');if(old&&z.players.some(p=>p.id==old))$('playerPick').value=old;renderPlayerInspector();renderHeatmap()}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderPlayerInspector(){const z=currentRace();if(!z)return;const p=z.players.find(x=>x.id==+$('playerPick').value)||z.players[0];$('playerFacts').innerHTML=`<h2>Player facts</h2><div class="metricline">Strategy <b style="float:right">${p.strategy}${p.bagAI?' / '+p.bagAI:''}</b></div><div class="metricline">Skill <b style="float:right">${(p.skill*100).toFixed(0)}%</b></div><div class="metricline">Finish <b style="float:right">${p.finalPosition}</b></div><div class="metricline">Average rolling effort <b style="float:right">${(p.averageEffort*100).toFixed(0)}%</b></div><div class="metricline">Sacrifice <b style="float:right">${p.sacrificeSeconds.toFixed(1)}s</b></div><div class="metricline">Voluntary losses <b style="float:right">${p.voluntaryLosses}</b></div><div class="metricline">Debt added <b style="float:right">${p.debtAdded.toFixed(0)}m</b></div><div class="metricline">Debt repaid <b style="float:right">${p.debtRepaid.toFixed(0)}m</b></div><div class="metricline">Final debt <b style="float:right">${p.finalDebt.toFixed(0)}m</b></div><div class="metricline">Grace-laundered losses <b style="float:right">${p.launderedLosses||0}</b></div><div class="metricline">Potential avoided debt <b style="float:right">${(p.avoidedDebt||0).toFixed(0)}m</b></div><div class="metricline">Low-intent grace time <b style="float:right">${(p.graceAbuseSeconds||0).toFixed(1)}s</b></div><div class="metricline">Credit spent <b style="float:right">${(p.creditSpent*100).toFixed(0)}</b></div><div class="metricline">Hits taken <b style="float:right">${p.hitsTaken}</b></div>`;
  $('raceContext').innerHTML=`<div class="metricline">System <b style="float:right">${z.mode==='v2'?'v2.1':z.mode}</b></div><div class="metricline">Simulation seed <b style="float:right">${z.seed}</b></div><div class="metricline">Track length <b style="float:right">${z.trackLength}</b></div><div class="metricline">Events in race <b style="float:right">${z.events.length}</b></div><div class="metricline">Snapshots / player <b style="float:right">${p.snapshots.length}</b></div><div class="metricline">Frozen steering schedule <b style="float:right">yes</b></div>`;
  $('erpChart').innerHTML=lineChart([p.snapshots.map(s=>[s.raceProgress,s.position]),p.snapshots.map(s=>[s.raceProgress,s.erp])],1,12,['Actual position','Effective reward position'],true);
  $('creditChart').innerHTML=lineChart([p.snapshots.map(s=>[s.raceProgress,s.credit*100]),p.snapshots.map(s=>[s.raceProgress,s.effort*100])],0,100,['Comeback credit','Rolling effort']);
  const maxDebt=Math.max(1,...p.snapshots.map(s=>s.debt));$('debtChart').innerHTML=lineChart([p.snapshots.map(s=>[s.raceProgress,s.debt])],0,maxDebt,['Voluntary disadvantage debt']);
  $('snapshotTable').innerHTML=`<table><thead><tr><th>Race</th><th>Pos</th><th>ERP</th><th>Credit</th><th>Rolling effort</th><th>Debt</th><th>Lap</th><th>Sacrifice</th><th>Vol. losses</th><th>Spent</th><th>Hits</th></tr></thead><tbody>${p.snapshots.map(s=>`<tr><td>${Math.round(s.raceProgress*100)}%</td><td>${s.position}</td><td>${s.erp.toFixed(2)}</td><td>${Math.round(s.credit*100)}%</td><td>${Math.round(s.effort*100)}%</td><td>${s.debt.toFixed(0)}m</td><td>${s.lap}</td><td>${s.sacrificeSeconds.toFixed(1)}s</td><td>${s.voluntaryLosses}</td><td>${Math.round(s.creditSpent*100)}</td><td>${s.hitsTaken}</td></tr>`).join('')}</tbody></table>`;
  const ev=z.events.filter(e=>e.player===p.id||e.attacker===p.id||e.target===p.id);$('eventLog').innerHTML=ev.length?ev.map(e=>`<div class="eventrow"><b>${e.time.toFixed(1)}s · ${e.type}</b><div class="tiny muted">${escapeHtml(JSON.stringify(e))}</div></div>`).join(''):`<div class="eventrow muted">No logged events for this player.</div>`;
}
function renderHeatmap(){const z=currentRace();if(!z)return;const cols=z.players[0]?.snapshots.length||0;let h=`<div class="heat" style="grid-template-columns:110px repeat(${cols},minmax(35px,1fr))"><div></div>${z.players[0].snapshots.map(s=>`<div class="tiny" style="text-align:center">${Math.round(s.raceProgress*100)}%</div>`).join('')}`;for(const p of z.players){h+=`<div class="tiny">P${p.id+1} ${p.strategy[0]}</div>`+p.snapshots.map(s=>`<div class="heatcell" style="background:color-mix(in srgb,var(--s1) ${Math.max(4,Math.round(s.credit*100))}%,var(--panel3))">${Math.round(s.credit*100)}</div>`).join('')}$('heatmap').innerHTML=h+'</div>'}

async function runLab(){const c=cfg();$('runBtn').disabled=true;$('status').textContent='Running paired Instant, V1, and V2.1 races…';await new Promise(r=>setTimeout(r,20));try{const raw={instant:[],v1:[],v2:[]},raceSeeds=[];for(let i=0;i<c.races;i++){const rosterSeed=hash(c.seed,i),simulationSeed=hash(c.seed+7717,i),ro=makeRoster(rosterSeed,c);raceSeeds.push({race:i+1,rosterSeed,simulationSeed});raw.instant.push(simulate(ro,c,'instant',simulationSeed,true));raw.v1.push(simulate(ro,c,'v1',simulationSeed,true));raw.v2.push(simulate(ro,c,'v2',simulationSeed,true));if(i%100===99){$('status').textContent=`Simulating… ${i+1}/${c.races}`;await new Promise(r=>setTimeout(r,0))}}archive={modelVersion:MODEL,createdAt:new Date().toISOString(),config:c,raceSeeds,summary:{instant:aggregate(raw.instant,'instant'),v1:aggregate(raw.v1,'v1'),v2:aggregate(raw.v2,'v2')},pairedHealth:pairedHealth(raw),races:raw,stress:null,exploitHunter:null};renderSummary();initInspector();await buildExports();$('status').textContent=`Complete: ${c.races.toLocaleString()} paired races · ${(c.races*36).toLocaleString()} driver-runs. MKF-C2Z report ready.`}catch(e){console.error(e);$('status').textContent='Simulation error: '+e.message}finally{$('runBtn').disabled=false}}

async function runStress(){if(!archive){$('status').textContent='Run the main lab first.';return}const base=archive.config,scenarios=[['Bagging invasion',{baggers:6,fronts:2}],['Elite technical',{skill:'elite',track:'technical',chaos:.75}],['Item storm',{track:'item',chaos:1.65,blue:1.5}],['Compressed pack',{track:'pack',pack:1}],['Stop-and-wait swarm',{bagAI:'stop',baggers:5}],['Pulse-braking swarm',{bagAI:'pulse',baggers:5}],['Credit-farming swarm',{bagAI:'farmer',baggers:5}],['Late-bag lobby',{bagAI:'late',baggers:5}]];$('stressOut').textContent='Running hostile scenarios…';$('stressBtn').disabled=true;await new Promise(r=>setTimeout(r,20));const out=[];for(let si=0;si<scenarios.length;si++){let[name,patch]=scenarios[si],c={...base,...patch,races:140,capture:'normal'},raw={instant:[],v1:[],v2:[]};for(let i=0;i<c.races;i++){const ro=makeRoster(hash(c.seed+si*1000,i),c),rs=hash(c.seed+8800+si*500,i);raw.instant.push(simulate(ro,c,'instant',rs,false));raw.v1.push(simulate(ro,c,'v1',rs,false));raw.v2.push(simulate(ro,c,'v2',rs,false))}const I=aggregate(raw.instant,'instant'),V1=aggregate(raw.v1,'v1'),V2=aggregate(raw.v2,'v2'),H=pairedHealth(raw),ib=pct(I.baggerTop3,I.baggerTrials);out.push({name,config:c,v1Top3Delta:pct(V1.baggerTop3,V1.baggerTrials)-ib,v2Top3Delta:pct(V2.baggerTop3,V2.baggerTrials)-ib,v2ComebackDelta:pct(H.v2.g4,H.v2.gN)-pct(H.instant.g4,H.instant.gN),v2ROI:roi(V2)});$('stressOut').textContent=`Running hostile scenarios… ${si+1}/${scenarios.length}`;await new Promise(r=>setTimeout(r,0))}archive.stress=out;$('stressOut').innerHTML=`<div class="scroll"><table><thead><tr><th>Scenario</th><th>V1 bag top-3 Δ</th><th>V2.1 bag top-3 Δ</th><th>Fixed-cohort comeback Δ</th><th>V2.1 ROI</th><th>Read</th></tr></thead><tbody>${out.map(x=>{let ok=x.v2Top3Delta<=-4&&x.v2ComebackDelta>=-6&&(x.v2ROI==null||x.v2ROI<0);return`<tr><td>${x.name}</td><td>${x.v1Top3Delta.toFixed(1)}</td><td><b>${x.v2Top3Delta.toFixed(1)}</b></td><td>${x.v2ComebackDelta.toFixed(1)}</td><td>${x.v2ROI==null?'—':x.v2ROI.toFixed(2)}</td><td class="${ok?'good':'warn'}">${ok?'PASS':'INSPECT'}</td></tr>`}).join('')}</tbody></table></div>`;await buildExports();$('stressBtn').disabled=false}

function attackDiagnostics(races){let baggerRuns=0,activated=0,launderedLosses=0,avoidedDebt=0,graceAbuseSeconds=0,nonBaggerRuns=0,nonBaggerDebt=0;for(const z of races)for(const p of z.players){if(p.strategy==='Bagger'){baggerRuns++;if((p.launderedLosses||0)>0)activated++;launderedLosses+=p.launderedLosses||0;avoidedDebt+=p.avoidedDebt||0;graceAbuseSeconds+=p.graceAbuseSeconds||0}else{nonBaggerRuns++;nonBaggerDebt+=p.debtAdded||0}}return{baggerRuns,activated,launderedLosses,avoidedDebt,graceAbuseSeconds,nonBaggerRuns,nonBaggerDebt,launderedPer100:pct(launderedLosses,baggerRuns),activationRate:pct(activated,baggerRuns),avoidedDebtPerRun:baggerRuns?avoidedDebt/baggerRuns:0,graceAbuseSecondsPerRun:baggerRuns?graceAbuseSeconds/baggerRuns:0,nonBaggerDebtPerRun:nonBaggerRuns?nonBaggerDebt/nonBaggerRuns:0}}
function balancedAttackTests(){const points=[{debt:40,window:3,eff:1.1},{debt:40,window:6,eff:1.55},{debt:60,window:4.5,eff:1.35},{debt:60,window:3,eff:1.55},{debt:80,window:4.5,eff:1.1},{debt:80,window:6,eff:1.35}],out=[];for(const ai of STANDARD_ATTACK_AIS)for(const q of points)out.push({ai,...q,grace:null});return out}
function fullAttackTests(){const out=[];for(const ai of STANDARD_ATTACK_AIS)for(const debt of[40,60,80])for(const window of[3,4.5,6])for(const eff of[1.1,1.35,1.55])out.push({ai,debt,window,eff,grace:null});return out}
function graceAttackTests(){const out=[];for(const grace of[0,1.4,2.8,4.2])for(const debt of[40,60,80])for(const window of[3,4.5,6])out.push({ai:GRACE_ATTACK_AI,debt,window,eff:1.35,grace});return out}
function attackRisk(delta,rr,d){return delta+Math.max(0,rr)*5+(d.launderedLosses/(d.baggerRuns||1))*2+(d.avoidedDebtPerRun/120)}
function attackTable(out,kind){const top=out[0],graceMode=kind==='grace';return`<div class="note"><b>Worst exploit signal:</b> ${top?`${top.parameters.ai}, debt ${top.parameters.debt}m/place, window ${top.parameters.window}s, effort ${top.parameters.eff}×${top.parameters.grace==null?'':`, grace ${top.parameters.grace}s`}`:'—'}<div class="tiny muted" style="margin-top:5px">Risk is a triage heuristic. ROI and top-3 impact determine whether abuse is actually profitable; laundering metrics show whether the loophole was exercised.</div></div><div class="scroll sectiongap"><table><thead><tr><th>AI</th><th>Debt</th><th>Window</th><th>Effort</th>${graceMode?'<th>Grace</th>':''}<th>V2.1 top-3</th><th>vs Instant</th><th>ROI</th><th>Launder / 100</th><th>Avoided debt/run</th><th>Non-bagger debt/run</th><th>Risk</th></tr></thead><tbody>${out.slice(0,20).map(x=>`<tr><td>${x.parameters.ai}</td><td>${x.parameters.debt}</td><td>${x.parameters.window}</td><td>${x.parameters.eff}</td>${graceMode?`<td>${x.parameters.grace}</td>`:''}<td>${x.v2Top3.toFixed(1)}%</td><td>${x.top3Delta.toFixed(1)}</td><td>${x.roi.toFixed(2)}</td><td>${x.diagnostics.launderedPer100.toFixed(1)}</td><td>${x.diagnostics.avoidedDebtPerRun.toFixed(1)}m</td><td>${x.diagnostics.nonBaggerDebtPerRun.toFixed(1)}m</td><td><b>${x.risk.toFixed(2)}</b></td></tr>`).join('')}</tbody></table></div>`}
async function runAttackSuite(kind){if(!archive){$('status').textContent='Run the main lab first.';return}const base=archive.config,tests=kind==='balanced'?balancedAttackTests():kind==='full'?fullAttackTests():graceAttackTests(),button=kind==='balanced'?$('huntBtn'):kind==='full'?$('fullHuntBtn'):$('graceHuntBtn'),target=kind==='balanced'?$('huntOut'):kind==='full'?$('fullHuntOut'):$('graceOut'),racesPer=kind==='full'?50:80;button.disabled=true;target.textContent=`${kind==='grace'?'Grace-abuse':kind==='full'?'Full':'Balanced'} attack running… 0/${tests.length}`;await new Promise(r=>setTimeout(r,20));const out=[];for(let ti=0;ti<tests.length;ti++){const q=tests[ti],c={...base,bagAI:q.ai,debtPerPlace:q.debt,effortWindow:q.window,effortSens:q.eff,grace:q.grace==null?base.grace:q.grace,baggers:5,races:racesPer,capture:'normal'},ri=[],rv=[];for(let i=0;i<c.races;i++){const ro=makeRoster(hash(c.seed+ti*731+(kind==='grace'?500000:kind==='full'?250000:0),i),c),rs=hash(c.seed+9999+ti*997+(kind==='grace'?700000:kind==='full'?350000:0),i);ri.push(simulate(ro,c,'instant',rs,false));rv.push(simulate(ro,c,'v2',rs,false))}const I=aggregate(ri,'instant'),V2=aggregate(rv,'v2'),ib=I.strategies.Bagger,vb=V2.strategies.Bagger,v2Top3=pct(vb.top3,vb.n),delta=v2Top3-pct(ib.top3,ib.n),rr=roi(V2)||0,d=attackDiagnostics(rv),risk=attackRisk(delta,rr,d);out.push({parameters:q,v2Top3,top3Delta:delta,roi:rr,diagnostics:d,risk});target.textContent=`${kind==='grace'?'Grace-abuse':kind==='full'?'Full':'Balanced'} attack running… ${ti+1}/${tests.length}`;await new Promise(r=>setTimeout(r,0))}out.sort((a,b)=>b.risk-a.risk);if(!archive.exploitHunter)archive.exploitHunter={balanced:null,full:null,grace:null};archive.exploitHunter[kind]={kind,racesPerConfig:racesPer,testCount:tests.length,results:out};target.innerHTML=attackTable(out,kind);await buildExports();button.disabled=false;$('status').textContent=`${kind==='grace'?'Grace-abuse':kind==='full'?'Full':'Balanced'} attack complete · ${tests.length} configurations.`}
async function runHunter(){return runAttackSuite('balanced')}
async function runFullHunter(){return runAttackSuite('full')}
async function runGraceHunter(){return runAttackSuite('grace')}

const qi=(x,s=1000)=>Math.round(Number(x||0)*s);
const SCHEMA={
  dict:{strategies:STR,bagAIs:AIS,items:ITEMS,tracks:['balanced','technical','item','straight','pack'],skills:['mixed','equal','elite','split'],captures:['normal','deep','frame']},
  scales:{ratio:1000,position100:100,timeTicksPerSecond:2,distanceMeters:1,debtMeters:1},
  config:['races','seed','baggers','fronts','track#','skill#','bagAI#','chaos*1000','pack*1000','blue*1000','lapAccel*1000','v1Strict*1000','distanceReq*1000','effortWindow*10','effortSens*1000','debtPerPlace','creditSpend*1000','frontDecay*1000','grace*10','capture#'],
  strategySummary:['n','finishSum*100','wins','top3','bottom4','powerSum*1000','items','sacrificeTicks','skillSum*1000'],
  aiSummary:['n','finishSum*100','wins','top3','bottom4','sacrificeTicks'],
  summary:['strategies[4]','bagAIs[6]','baggerTrials','baggerTop3','baggerWins','baggerBottom4','skillCorrelation*1000','adjustedSacrificeSlope*1000'],
  pairedHealth:['genuineN','genuineTop4','frontN','frontTop3','displacementN','displacement'],
  player:['id','strategy#','bagAI#','skill*1000','itemSkill*1000','consistency*1000','aggression*1000','risk*1000','finalPosition','finishTicks','bagged','sacrificeTicks','voluntaryLosses','validatedLossStreak','debtAddedM','debtRepaidM','finalDebtM','launderedLosses','avoidedDebtM','graceAbuseTicks','creditSpent*1000','hitsTaken','avgEffort*1000','avgItemPower*1000','itemCount','snapshots','frames|null'],
  snapshot:['progressPct','position','erp*100','credit*1000','effort*1000','debtM','distanceM','lap','sacrificeTicks','voluntaryLosses','validatedLossStreak','creditSpent*1000','hitsTaken'],
  frame:['timeTicks','position','erp*100','credit*1000','effort*1000','debtM','distanceM','lap','sacrificeTicks','voluntaryLosses','creditSpent*1000','hitsTaken'],
  eventTypes:{0:'item_draw',1:'hit',2:'track_disruption',3:'position_loss_classified',4:'finish',5:'debt_cleared'},
  lossEvent:['type#','timeTicks','player','from','to','validated','rollingEffort*1000','driverIntent*1000','inGrace','graceLaundered','graceLeft*10','creditAfter*1000','erp*100','debtAddedM','debtM','avoidedDebtM']
};
function packStrategy(s){return[s.n,qi(s.finish,100),s.wins,s.top3,s.bottom4,qi(s.power),s.items,qi(s.sacrifice,2),qi(s.skill)]}
function packAI(s){return[s.n,qi(s.finish,100),s.wins,s.top3,s.bottom4,qi(s.sacrifice,2)]}
function packSummary(s){return[STR.map(k=>packStrategy(s.strategies[k])),AIS.slice(1).map(a=>packAI(s.bagAI[a])),s.baggerTrials,s.baggerTop3,s.baggerWins,s.baggerBottom4,qi(s.skillCorrelation),qi(s.adjustedSacrificeSlope)]}
function packHealth(h){return[h.gN,h.g4,h.fN,h.f3,h.dN,h.disp]}
function packSnap(s){return[qi(s.raceProgress,100),s.position,qi(s.erp,100),qi(s.credit),qi(s.effort),Math.round(s.debt),Math.round(s.distance),s.lap,qi(s.sacrificeSeconds,2),s.voluntaryLosses,s.validatedLossStreak,qi(s.creditSpent),s.hitsTaken]}
function packFrame(f){return[qi(f.time,2),f.position,qi(f.erp,100),qi(f.credit),qi(f.effort),Math.round(f.debt),Math.round(f.distance),f.lap,qi(f.sacrificeSeconds,2),f.voluntaryLosses,qi(f.creditSpent),f.hitsTaken]}
function packPlayer(p){return[p.id,STR.indexOf(p.strategy),AIS.indexOf(p.bagAI),qi(p.skill),qi(p.itemSkill),qi(p.consistency),qi(p.aggression),qi(p.risk),p.finalPosition,qi(p.finishTime,2),p.bagged?1:0,qi(p.sacrificeSeconds,2),p.voluntaryLosses,p.validatedLossStreak,Math.round(p.debtAdded),Math.round(p.debtRepaid),Math.round(p.finalDebt),p.launderedLosses||0,Math.round(p.avoidedDebt||0),qi(p.graceAbuseSeconds||0,2),qi(p.creditSpent),p.hitsTaken,qi(p.averageEffort),qi(p.averageItemPower),p.itemCount,p.snapshots.map(packSnap),p.frames?p.frames.map(packFrame):null]}
function packEvent(e){const typeMap={item_draw:0,hit:1,track_disruption:2,position_loss_classified:3,finish:4,debt_cleared:5},t=typeMap[e.type]??9;if(t===0)return[0,qi(e.time,2),e.player,ITEMS.indexOf(e.item),e.position,qi(e.erp,100),qi(e.creditAfter),Math.round(e.debt),qi(e.rollingEffort),qi(e.power),qi(e.creditCost),Math.round(e.distance),e.lap,e.opening?1:0];if(t===1)return[1,qi(e.time,2),e.attacker,e.target,ITEMS.indexOf(e.item),e.attackerPosition,e.targetPosition,qi(e.targetGrace,10),Math.round(e.distance)];if(t===2)return[2,qi(e.time,2),e.player,e.position,qi(e.grace,10),Math.round(e.distance)];if(t===3)return[3,qi(e.time,2),e.player,e.from,e.to,e.validated?1:0,qi(e.rollingEffort),qi(e.driverIntent),e.inGrace?1:0,e.graceLaundered?1:0,qi(e.graceLeft,10),qi(e.creditAfter),qi(e.erp,100),Math.round(e.debtAdded),Math.round(e.debt),Math.round(e.avoidedDebt||0)];if(t===4)return[4,qi(e.time,2),e.player,e.finalPosition];if(t===5)return[5,qi(e.time,2),e.player,Math.round(e.totalRepaid)];return[9,e]}
function packRace(r){return[r.seed,r.trackLength,r.players.map(packPlayer),r.events.map(packEvent)]}
function compactArchive(){const c=archive.config,tracks=SCHEMA.dict.tracks,skills=SCHEMA.dict.skills,caps=SCHEMA.dict.captures;return['MKF-C2',MODEL,SCHEMA,[c.races,c.seed,c.baggers,c.fronts,tracks.indexOf(c.track),skills.indexOf(c.skill),AIS.indexOf(c.bagAI),qi(c.chaos),qi(c.pack),qi(c.blue),qi(c.lapAccel),qi(c.v1Strict),qi(c.distanceReq),qi(c.effortWindow,10),qi(c.effortSens),Math.round(c.debtPerPlace),qi(c.creditSpend),qi(c.frontDecay),qi(c.grace,10),caps.indexOf(c.capture)],archive.raceSeeds.map(x=>[x.race,x.rosterSeed,x.simulationSeed]),[packSummary(archive.summary.instant),packSummary(archive.summary.v1),packSummary(archive.summary.v2)],[packHealth(archive.pairedHealth.instant),packHealth(archive.pairedHealth.v1),packHealth(archive.pairedHealth.v2)],archive.stress,archive.exploitHunter,[archive.races.instant.map(packRace),archive.races.v1.map(packRace),archive.races.v2.map(packRace)]]}
function downloadFile(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function gzipBase64(text){if(typeof CompressionStream==='undefined')return null;const stream=new Blob([text],{type:'text/plain'}).stream().pipeThrough(new CompressionStream('gzip'));const ab=await new Response(stream).arrayBuffer(),bytes=new Uint8Array(ab);let bin='';for(let i=0;i<bytes.length;i+=32768)bin+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(bin)}
async function buildExports(){if(!archive)return;const compact=JSON.stringify(compactArchive());let eventCount=0,frameCount=0;for(const mode of['instant','v1','v2'])for(const r of archive.races[mode]){eventCount+=r.events.length;for(const p of r.players)frameCount+=p.frames?.length||0}$('exportStats').innerHTML=`<div class="subcard"><div class="tiny muted">System-races</div><b>${(archive.config.races*3).toLocaleString()}</b></div><div class="subcard"><div class="tiny muted">Driver-runs</div><b>${(archive.config.races*36).toLocaleString()}</b></div><div class="subcard"><div class="tiny muted">Logged events</div><b>${eventCount.toLocaleString()}</b></div><div class="subcard"><div class="tiny muted">Frame records</div><b>${frameCount.toLocaleString()}</b></div>`;
  let packed=null;try{packed=await gzipBase64(compact)}catch(e){console.warn('CompressionStream failed, using plain C2',e)}
  if(packed){primaryReportText='MKF-C2Z|'+packed;primaryReportName=`mario-kart-MKF-C2Z-${archive.config.seed}.txt`;$('downloadCompact').textContent='Download MKF-C2Z report'}else{primaryReportText='MKF-C2|1/1|'+compact;primaryReportName=`mario-kart-MKF-C2-${archive.config.seed}.txt`;$('downloadCompact').textContent='Download MKF-C2 report'}
  $('downloadCompact').disabled=false;$('downloadJson').disabled=false;$('downloadNdjson').disabled=false;$('selectDigest').disabled=false;$('downloadCompact').onclick=()=>downloadFile(primaryReportName,primaryReportText,'text/plain');$('downloadJson').onclick=()=>downloadFile(`mario-kart-raw-${archive.config.seed}.json`,JSON.stringify(archive),'application/json');$('downloadNdjson').onclick=()=>{const lines=[];for(const mode of['instant','v1','v2'])archive.races[mode].forEach((r,i)=>r.events.forEach(e=>lines.push(JSON.stringify({mode,race:i+1,seed:r.seed,...e}))));downloadFile(`mario-kart-events-${archive.config.seed}.ndjson`,lines.join('\n'),'application/x-ndjson')};
  const size=60000,total=Math.max(1,Math.ceil(primaryReportText.length/size));compactChunks=[];for(let i=0;i<total;i++)compactChunks.push(`${packed?'MKF-C2Z':'MKF-C2'}|${i+1}/${total}|`+primaryReportText.slice(i*size,(i+1)*size));chunkIndex=0;showChunk();
  $('compressionInfo').textContent=packed?`Plain MKF-C2: ${compact.length.toLocaleString()} chars · compressed text: ${primaryReportText.length.toLocaleString()} chars · ${(100*(1-primaryReportText.length/compact.length)).toFixed(1)}% smaller · ${total} copy chunk(s).`:`MKF-C2: ${compact.length.toLocaleString()} characters · ${total} copy chunk(s). Native gzip was unavailable, so this run uses the plain fallback.`;
  const I=archive.summary.instant,V1=archive.summary.v1,V2=archive.summary.v2,H=archive.pairedHealth;$('digest').value=[`MARIO KART LAB — ${MODEL}`,`Config: ${JSON.stringify(archive.config)}`,`Bagger top-3 I/V1/V2.1: ${pct(I.baggerTop3,I.baggerTrials).toFixed(2)} / ${pct(V1.baggerTop3,V1.baggerTrials).toFixed(2)} / ${pct(V2.baggerTop3,V2.baggerTrials).toFixed(2)}`,`Bagger wins I/V1/V2.1: ${pct(I.baggerWins,I.baggerTrials).toFixed(2)} / ${pct(V1.baggerWins,V1.baggerTrials).toFixed(2)} / ${pct(V2.baggerWins,V2.baggerTrials).toFixed(2)}`,`Fixed comeback I/V1/V2.1: ${pct(H.instant.g4,H.instant.gN).toFixed(2)} / ${pct(H.v1.g4,H.v1.gN).toFixed(2)} / ${pct(H.v2.g4,H.v2.gN).toFixed(2)}`,`Fixed front retention I/V1/V2.1: ${pct(H.instant.f3,H.instant.fN).toFixed(2)} / ${pct(H.v1.f3,H.v1.fN).toFixed(2)} / ${pct(H.v2.f3,H.v2.fN).toFixed(2)}`,`V2.1 ROI: ${roi(V2)==null?'n/a':roi(V2).toFixed(3)}`,`V2.1 adjusted sacrifice slope: ${V2.adjustedSacrificeSlope.toFixed(3)}`,`Stress included: ${archive.stress?'yes':'no'}`,`Attack suites: ${archive.exploitHunter?Object.entries(archive.exploitHunter).filter(([,v])=>v).map(([k])=>k).join(', ')||'none':'none'}`,`Primary forensic format: ${packed?'MKF-C2Z':'MKF-C2'}`,`Copy chunks: ${total}`].join('\n')}
function showChunk(){if(!compactChunks.length)return;$('compactText').value=compactChunks[chunkIndex];$('chunkLabel').textContent=`Chunk ${chunkIndex+1} / ${compactChunks.length}`;$('prevChunk').disabled=chunkIndex===0;$('nextChunk').disabled=chunkIndex===compactChunks.length-1;$('selectChunk').disabled=false}
function syncLabels(){$('chaosTxt').textContent=(+$('chaos').value).toFixed(1)+'×';$('packTxt').textContent=Math.round(+$('pack').value*100)+'%';const b=+$('blue').value;$('blueTxt').textContent=b===0?'Off':b===1?'Normal':b.toFixed(2)+'×';$('lapTxt').textContent=Math.round(+$('lapAccel').value*100)+'%';$('v1Txt').textContent=(+$('v1Strict').value).toFixed(2)+'×';$('distTxt').textContent=(+$('distanceReq').value).toFixed(2)+'×';$('windowTxt').textContent=(+$('effortWindow').value).toFixed(1)+'s';$('effTxt').textContent=(+$('effortSens').value).toFixed(2)+'×';$('debtTxt').textContent=Math.round(+$('debtPerPlace').value)+'m';$('spendTxt').textContent=(+$('creditSpend').value).toFixed(2)+'×';$('decayTxt').textContent=(+$('frontDecay').value*100).toFixed(1)+'%/s';$('graceTxt').textContent=(+$('grace').value).toFixed(1)+'s'}

$$('input[type=range]').forEach(x=>x.addEventListener('input',syncLabels));$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.panel))}));$('capture').addEventListener('change',()=>{if($('capture').value==='frame'&&+$('races').value>100){$('races').value=100;$('status').textContent='Full-frame capture selected: race count capped at 100.'}});$('runBtn').addEventListener('click',runLab);$('stressBtn').addEventListener('click',runStress);$('huntBtn').addEventListener('click',runHunter);$('fullHuntBtn').addEventListener('click',runFullHunter);$('graceHuntBtn').addEventListener('click',runGraceHunter);$('inspectMode').addEventListener('change',renderRaceInspector);$('racePick').addEventListener('change',renderRaceInspector);$('playerPick').addEventListener('change',renderPlayerInspector);$('prevChunk').addEventListener('click',()=>{if(chunkIndex>0){chunkIndex--;showChunk()}});$('nextChunk').addEventListener('click',()=>{if(chunkIndex<compactChunks.length-1){chunkIndex++;showChunk()}});$('selectChunk').addEventListener('click',()=>{$('compactText').focus();$('compactText').select()});$('selectDigest').addEventListener('click',()=>{$('digest').focus();$('digest').select()});syncLabels();
})();
